document.documentElement.classList.add("js");
window.addEventListener("load",()=>{setTimeout(()=>document.body.classList.add("loaded"),450)});
const nav=document.querySelector(".nav");window.addEventListener("scroll",()=>nav&&nav.classList.toggle("scrolled",scrollY>30));
const menuBtn=document.getElementById("menuBtn"),mobileMenu=document.getElementById("mobileMenu");menuBtn?.addEventListener("click",()=>mobileMenu.classList.toggle("open"));mobileMenu?.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>mobileMenu.classList.remove("open")));
const theme=document.getElementById("themeToggle");const saved=localStorage.getItem("snap-theme");if(saved==="light")document.body.classList.add("light");theme?.addEventListener("click",()=>{document.body.classList.toggle("light");localStorage.setItem("snap-theme",document.body.classList.contains("light")?"light":"dark")});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
document.querySelectorAll("[data-count]").forEach(el=>{const io=new IntersectionObserver(es=>{if(es[0].isIntersecting){let n=0,end=+el.dataset.count;const t=setInterval(()=>{n+=Math.ceil(end/55);if(n>=end){n=end;clearInterval(t)}el.textContent=n.toLocaleString()+"+"},25);io.disconnect()}},{threshold:.6});io.observe(el)});
document.querySelectorAll(".magnetic").forEach(btn=>btn.addEventListener("mousemove",e=>{const r=btn.getBoundingClientRect();btn.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.12}px)`}),btn.addEventListener("mouseleave",()=>btn.style.transform=""));
const form=document.getElementById("quoteForm");form?.addEventListener("submit",e=>{e.preventDefault();const data=new FormData(form);const msg=`Hi Snap Studio & Digital Arts,%0A%0AName: ${data.get("name")}%0APhone: ${data.get("phone")}%0ABusiness: ${data.get("business")}%0ACategory: ${data.get("category")}%0ABudget: ${data.get("budget")}%0AService: ${data.get("service")}%0A%0AMessage: ${data.get("message")}`;document.getElementById("formNote").textContent="Enquiry prepared. Opening WhatsApp…";window.open(`https://wa.me/919322410521?text=${msg}`,"_blank");});
